import { Class } from '@/types'

// Mock class data
export const mockClasses: Class[] = [
  {
    id: 'mt-fund-001',
    title: 'Muay Thai Fundamentals',
    discipline: 'muay-thai',
    instructor: 'Shaleena',
    date: '2026-02-03',
    time: '18:00',
    duration: 60,
    credits: 1,
    spotsAvailable: 8,
    level: 'beginner',
  },
  {
    id: 'mt-cond-001',
    title: 'Muay Thai Conditioning',
    discipline: 'muay-thai',
    instructor: 'Shaleena',
    date: '2026-02-04',
    time: '06:00',
    duration: 60,
    credits: 1,
    spotsAvailable: 12,
    level: 'all-levels',
  },
  {
    id: 'mt-tech-001',
    title: 'Muay Thai Technique',
    discipline: 'muay-thai',
    instructor: 'Shaleena',
    date: '2026-02-05',
    time: '18:30',
    duration: 75,
    credits: 1,
    spotsAvailable: 6,
    level: 'intermediate',
  },
  {
    id: 'lyra-basic-001',
    title: 'Lyra Basics',
    discipline: 'aerial',
    instructor: 'Tinsley',
    date: '2026-02-06',
    time: '19:30',
    duration: 90,
    credits: 2,
    spotsAvailable: 4,
    level: 'beginner',
  },
  {
    id: 'silks-intro-001',
    title: 'Aerial Silks Intro',
    discipline: 'aerial',
    instructor: 'Tinsley',
    date: '2026-02-03',
    time: '17:00',
    duration: 90,
    credits: 2,
    spotsAvailable: 5,
    level: 'beginner',
  },
  {
    id: 'pole-inter-001',
    title: 'Pole Intermediate',
    discipline: 'aerial',
    instructor: 'Tinsley',
    date: '2026-02-04',
    time: '19:00',
    duration: 90,
    credits: 2,
    spotsAvailable: 3,
    level: 'intermediate',
  },
  {
    id: 'hammock-flow-001',
    title: 'Hammock Flow',
    discipline: 'aerial',
    instructor: 'Tinsley',
    date: '2026-02-05',
    time: '18:00',
    duration: 90,
    credits: 2,
    spotsAvailable: 6,
    level: 'all-levels',
  },
  {
    id: 'mt-spar-001',
    title: 'Muay Thai Sparring',
    discipline: 'muay-thai',
    instructor: 'Shaleena',
    date: '2026-02-06',
    time: '17:00',
    duration: 90,
    credits: 1,
    spotsAvailable: 10,
    level: 'advanced',
  },
]

// Mock user data
export const mockUser = {
  id: 'user-001',
  name: 'Alex Chen',
  email: 'alex@example.com',
  credits: 12,
  creditsExpiring: [
    { amount: 3, date: '2026-02-28' },
  ],
}

// Mock booking history
export const mockBookingHistory = [
  {
    id: 'booking-001',
    userId: 'user-001',
    classId: 'silks-intro-001',
    classTitle: 'Aerial Silks Intro',
    date: '2026-01-30',
    time: '17:00',
    credits: 2,
    status: 'confirmed' as const,
  },
  {
    id: 'booking-002',
    userId: 'user-001',
    classId: 'mt-cond-001',
    classTitle: 'Muay Thai Conditioning',
    date: '2026-01-28',
    time: '06:00',
    credits: 1,
    status: 'confirmed' as const,
  },
  {
    id: 'booking-003',
    userId: 'user-001',
    classId: 'pole-inter-001',
    classTitle: 'Pole Foundations',
    date: '2026-01-25',
    time: '19:00',
    credits: 2,
    status: 'confirmed' as const,
  },
]
